This PR fixes the import statement used in example code in README file
Kandy-IO/kandy-js-support pull request #7
Opened 2020-10-16 17:01 UTC by octavian-sandru

2020-10-16 20:04 UTC, jyboudreau requested changes

2020-10-16 20:04 UTC, jyboudreau commented on packages/link-config-emea/CHANGELOG.md
> +## 1.0.1
Let's just leave this version as `Unreleased` until we actually release it.
```suggestion
## Unreleased
```

2020-10-16 20:04 UTC, jyboudreau commented on packages/link-config-emea/CHANGELOG.md
> +- Fixed the import statement as part of example code used in README.
```suggestion
- Fixed the import statement of the example code in the README.
```

Let's change the others as well.

2020-10-21 12:02 UTC, MichelSimonot approved these changes

2020-10-21 12:55 UTC, merged